repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.800'
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
      - id: check-json
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
      - id: check-added-large-files
        args: ['--maxkb=5000', '--enforce-all']
