version: 0.2

env:
  shell: bash
  variables:
    REPOSITORY_URI: 'provided-by-server-environment'

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo "Starting Docker build `date` in `pwd`"
      - echo Building the Docker image...
      - docker build -t remixer:latest .
      - docker tag remixer:latest $REPOSITORY_URI:latest
      - echo Build completed on `date`
      - echo "Pushing to repo uri $REPOSITORY_URI"
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - echo "--------BUILD DONE.--------"
